# Zone management
tew_json_findzone:
  pattern: /zone/bycountry
  defaults: { _controller: TEWTPBundle:CountryZone:jsonFindZoneByCountry }
  requirements: { _method: post }

# Tag management
tew_json_allcandidatetags:
  pattern: /tags/allcandidate
  defaults: { _controller: TEWTPBundle:Tagging:jsonFindCandidateTags }
  requirements: { _method: get }
