# FrontEnd routes
tp_home:
    path:       /
    defaults:   { _controller: TEWTPBundle:Home:index }
    
tp_contact:
    path:       /contact
    defaults:   { _controller: TEWTPBundle:Home:contact }

# Company routes
TEWTPBundle_tew_company:
        resource: "@TEWTPBundle/Resources/config/routing/company.yml"
        prefix:   /tew_company
        
# Candidates routes
TEWTPBundle_tew_candidate:
    resource: "@TEWTPBundle/Resources/config/routing/candidate.yml"
    prefix:   /tew_candidate
    
# Talent pools routes
TEWTPBundle_tew_talentpool:
    resource: "@TEWTPBundle/Resources/config/routing/talentpool.yml"
    prefix:   /tew_talentpool

# Ajax routes
TEWTPBundle_tew_ajaxrequests:
    resource: "@TEWTPBundle/Resources/config/routing/ajaxrequests.yml"
    prefix:   /tew_ajax

# Statistics routes
TEWTPBundle_tew_statistics:
    resource: "@TEWTPBundle/Resources/config/routing/statistics.yml"
    prefix:   /tew_statistics
