imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc


monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

# Backup configuration
dizda_cloud_backup:
    # By default backup files will have your servers hostname as prefix
    # such as: hostname_2014-01-01_21-08-39.tar
    output_file_prefix: tew_prod
    processor:
        type: tar
        options:
            password: %dizda_cloud_archive_password%
    #folders: [ web/uploads , other/folder ]
    folders: [ web/uploads ]
    cloud_storages:
        # Local storage definition
        local:
            path: /srv/123vpc-backup/tew
    databases:
        mysql:
            all_databases: false
            database: talentpool_prod