# app/config/config.yml

imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    
    # Sonata Core Bundles
    - { resource: sonata/sonata_core.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_classification.yml }

    
    # Sonata Feature Bundles
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_user.yml }
    
    # Other stuff
    - { resource: other/doctrine_extensions.yml }
#    - { resource: other/ckeditor.yml }

framework:
    #esi:             ~
    translator:
        fallback:           "%locale%"
    secret:                 "%secret%"
    router:
        resource:           "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:                   ~
    csrf_protection:        ~
    validation:
        enable_annotations: true
    templating:
        engines:            ['twig']
        #assets_version: SomeVersionScheme
    default_locale:         "%locale%"
    trusted_proxies:        ~
    session:                ~
    fragments:              ~
    http_method_override:   true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            # other files
            - 'SonataMediaBundle:Form:media_widgets.html.twig'
            - 'TEWTPBundle:Form:tew_widgets.html.twig'
   

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
    
        entity_managers:
            default:
                #auto_mapping: true
                mappings: # to be declared for each entity in MySQL DB
                    ApplicationSonataMediaBundle: ~
                    TEWTPBundle: ~
                    TEWUserBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~
                    SonataMediaBundle: ~
                    SonataClassificationBundle: ~
                    #FogsTaggingBundle: ~
                    taggable:
                            type: annotation
                            prefix: DoctrineExtensions\Taggable\Entity
                            dir: "%kernel.root_dir%/../vendor/fpn/doctrine-extensions-taggable/metadata"
                    # GEDMO extensions ->
                    translatable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Translatable\Entity
                        # make sure vendor library location is correct
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                    loggable:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                    tree:
                        type: annotation
                        alias: Gedmo
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                    # <- GEDMO extensions

#doctrine_phpcr:
#    odm:
#        auto_mapping: true
#        mappings:
#            SonataMediaBundle:
#                prefix: Sonata\MediaBundle\PHPCR
                
# migrating entities after they've been modified
# (see app/console doctrine:migrations:diff)
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
#    spool:     { type: memory }
    spool:
        type: file
        path: "%kernel.root_dir%/spool"
    antiflood:
        threshold:  40
        sleep:      0
    logging: %kernel.debug%

# FOSUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: TEW\UserBundle\Entity\User
    group:
        group_class: TEW\UserBundle\Entity\Group
        group_manager: sonata.user.orm.group_manager
    from_email:
        address: webmaster@tew-cc.com
        sender_name: TEW webmaster
    service:
        user_manager: sonata.user.orm.user_manager

# Tag management
fpn_tag:
    model:
        tag_class:     \TEW\TPBundle\Entity\Tag
        tagging_class: \TEW\TPBundle\Entity\Tagging

## Sonata TP Bundle configuration
#sonata_tp:
#    security_acl:           false
#
#    manager_type: orm # Can be orm or mongodb
#
#    class:                  # Entity Classes
#        language:           TEW\TPBundle\Entity\Language
#
#    admin:                  # Admin Classes
#        language:
#            class:          TEW\TPBundle\Admin\LanguageAdmin
#            controller:     SonataAdminBundle:CRUD
##            translation:    SonataUserBundle
            

#templates:
#    layout: SonataAdminBundle::standard_layout_override.html.twig

# Customizing Sonata admin classes
parameters:
#    sonata.user.admin.user.class: TEW\UserBundle\Admin\UserAdmin
#    sonata.user.admin.user.entity: TEW\UserBundle\Entity\User

#    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\UserAdmin
#    sonata.user.admin.user.entity: Application\Sonata\UserBundle\Entity\User

# Services (see src/TEW/TPBundle/Ressources/config/services.yml)
services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
#    tew.admin.user:
#        class: TEW\UserBundle\Admin\UserAdmin
#        tags:
#            - { name: sonata.admin, manager_type: doctrine_orm, group: "Content", label: "User" }
#        arguments:
#            - ~
#            - Acme\MediaBundle\Document\Media
#            - '%sonata.media.admin.media.controller%'
#            - @sonata.media.pool