# Web console
_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console
    
# TEWUserBundle routes
_tew_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing/routing.yml"

# TEWTPBundle routes
_tew_tp:
    resource: "@TEWTPBundle/Resources/config/routing.yml"
    
## Tags management
#fogs_tag:
#    resource: "@FogsTaggingBundle/Controller"
#    type:     annotation
#    prefix:   /

# SonataAdminBundle routes
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
# app:
#    resource: @AppBundle/Controller/
#    type:     annotation

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin