# Sonata admin configuration
sonata_admin:
    title: backoffice
    title_logo: /bundles/tewtp/images/icons/tew.png
#    dashboard:
#        blocks:
#            # display a dashboard block
#            - { position: left, type: sonata.admin.block.admin_list }
#        groups:
#            admin:
#                label: Users
#            tp:
#                label: Languages