# Sonata Media management
sonata_media:
    # if you don't use default namespace configuration
    # class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:  # the default context is mandatory
            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                adminthumb: { width: 40 , quality: 70}
                thumbnail: { width: 20 , quality: 70}
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                
        candidate:  # the default context is mandatory
            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                adminthumb: { width: 40 , quality: 70}
                thumbnail: { width: 20 , quality: 70}
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}                
                
        # admin stuff
        sonata_collection:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        file:
            resizer: false
            filesystem: sonata.media.filesystem.local
            cdn: sonata.media.cdn.server
            generator: sonata.media.generator.default
            thumbnail: sonata.media.thumbnail.format
            allowed_extensions: ['pdf', 'doc', 'docx']
            allowed_mime_types: ['application/pdf', 'application/x-pdf', 'application/msword']