# TEW/app/config/sonata/sonata_admin.yml
# Sonata admin configuration
sonata_admin:
    title: backoffice
    title_logo: /bundles/tewtp/images/icons/tew.png

#    security:
#        in order to override the isGranted method with own voters...
#        handler: sonata.admin.security.handler.role
        
     # default value, change it to sonata.admin.security.handler.acl to use ACL
#    security:
#        handler: sonata.admin.security.handler.acl
#        # acl security information
#        information:
#            GUEST: [VIEW, LIST]
#            STAFF: [EDIT, LIST, CREATE]
#            EDITOR: [OPERATOR, EXPORT]
#            ADMIN: [MASTER]
    dashboard:
        blocks:
            # display a dashboard block
            - 
                position: top
                class: col-md-6
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Welcome to the TEW Backoffice</h2>
#            -
#                position: top
#                class: col-md-6
#                type: sonata.admin.block.search_result

            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ tew.admin.group.global, tew.admin.group.data ]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [ tew.admin.group.users, tew.admin.group.misc ]

        groups:
            tew.admin.group.global:
                label: global parameters
                icon: '<i class="fa fa-th"></i>'  
                items:
#                    - tew_tp.admin.language
                    - tew_tp.admin.cdtefunction
                    - tew_tp.admin.cdtelevel
                    - tew_tp.admin.cdtestatus
#                    - tew_tp.admin.cdtelanguage
            tew.admin.group.data:
                label: Pools & Candidates
                icon: '<i class="fa fa-th"></i>'
                items:
                    - tew_tp.admin.talentpool
                    - tew_tp.admin.candidate
            tew.admin.group.users:
                label: Users
                icon: '<i class="fa fa-th"></i>'
                items:
                    #- sonata.user.admin.user
                    - tew_user.admin.users
            tew.admin.group.misc:
                label: Misc parameters
                icon: '<i class="fa fa-th"></i>'
                items:
                    - sonata.classification.admin.context
                    - sonata.classification.admin.category
                    - sonata.classification.admin.collection
                    - sonata.media.admin.media
                
#        groups:
#            admin:
#                label: Users
#            tp:
#                label: Languages
    templates:
        # other configuration options
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig