# Sonata User configuration
sonata_user:
    security_acl:           false

    manager_type: orm # Can be orm or mongodb

#    table:
#        user_group: "my_custom_user_group_association_table_name"
#
#    impersonating:
#        route:                page_slug
#        parameters:           { path: / }

    class:                  # Entity Classes
        user:               TEW\UserBundle\Entity\User
        group:              TEW\UserBundle\Entity\Group
        
    impersonating:
        route: tp_home

    admin:                  # Admin Classes
        user:
#            class:          Sonata\UserBundle\Admin\Entity\UserAdmin
            class:          TEW\UserBundle\Admin\UserAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle

        group:
            class:          Sonata\UserBundle\Admin\Entity\GroupAdmin
            controller:     SonataAdminBundle:CRUD
            translation:    SonataUserBundle