security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    
    providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: fos_user.user_manager # doc sonata
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|tew_ajax)/
            security: false
            
        login:
            pattern:   ^/(login$|register|resetting)  # authorizing anonymous acces to theses pages
            anonymous: true     
            
        admin:
            pattern:            /admin(.*)
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     /admin/login
                use_forward:    false
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                invalidate_session: false # PHP 5.4.10 bug solved by setting this
            anonymous:          true

        main:
            pattern: .*
            form_login:
                provider:       fos_userbundle
                csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:   null
                remember_me:    true
                default_target_path: fos_user_profile_show
            remember_me:
                    key:        %secret%
                    lifetime:   3600 # in seconds
                    path:       /
                    domain:     ~
            logout:
                invalidate_session: false # PHP 5.4.10 bug solved by setting this
                path:           fos_user_security_logout
                target:         tp_home
            anonymous:          false
