<?php

namespace TEW\TPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileMobilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileMobilityRepository extends EntityRepository
{
}
