<?php

namespace TEW\TPBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * TalentPoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TalentPoolRepository extends EntityRepository
{
    public function countCandidatesByTalentPool($id) {
        $rsm = new ResultSetMapping();
        $rsm->addScalarResult('nb', 'nb', 'integer');
        $query = $this->getEntityManager()->createNativeQuery("SELECT COUNT(tc.candidate_id) as nb "
                . "FROM tew_talentpool_candidates tc "
                . "WHERE tc.talentpool_id = ?",
                $rsm);
        $query->setParameter(1, $id);
        
        $result = $query->getResult();
        return $result[0]['nb'];
    }
}
