<?php

namespace TEW\TPBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends EntityRepository {

    /**
     * Return the zone associated to a given country
     *
     */
    public function findZoneByCountry($country) {
        $qb = $this->createQueryBuilder('z')
                ->select('z.id', 'z.fullname')
                ->join('TEWTPBundle:CountryZone', 'zc')
                ->where("zc.country = :country")
                ->andWhere('zc.zone = z.id')
                ->setParameter('country', $country);
        $query = $qb->getQuery();
        return $query->getResult();
    }
}
